//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"
import { createTypeScriptImportResolver } from "eslint-import-resolver-typescript"

export default [
  ...tanstackConfig,
  {
    // Resolve the `@/` alias (tsconfig paths) so import/no-restricted-paths
    // can map aliased imports to files and enforce the feature boundaries.
    // eslint-plugin-import-x reads the new-style resolver-next key.
    settings: {
      "import-x/resolver-next": [
        createTypeScriptImportResolver({ project: "./tsconfig.json" }),
      ],
    },
  },
  {
    rules: {
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
      // Bulletproof-react boundaries (#61): dependencies flow one way only —
      // shared → features → routes. A feature can't reach into a sibling
      // feature; shared code (components, lib) can't import a feature; and
      // nothing outside routes/ may import a route. Cross-feature composition
      // happens only in the route layer.
      "import/no-restricted-paths": [
        "error",
        {
          zones: [
            {
              target: "./src/features/auth",
              from: "./src/features",
              except: ["./auth"],
            },
            {
              target: "./src/features/logger",
              from: "./src/features",
              except: ["./logger"],
            },
            {
              target: "./src/features/manage",
              from: "./src/features",
              except: ["./manage"],
            },
            {
              target: "./src/features/dashboard",
              from: "./src/features",
              except: ["./dashboard"],
            },
            {
              target: ["./src/components", "./src/lib"],
              from: "./src/features",
            },
            {
              target: ["./src/components", "./src/lib", "./src/features"],
              from: "./src/routes",
            },
            // The story harness is a #storybook/* alias in the same tsconfig
            // paths block the app uses, so nothing stopped a route importing
            // the fixture cast — typecheck, lint and build all passed, and
            // the fixtures shipped to dist/client. Now they don't.
            { target: "./src", from: "./.storybook" },
          ],
        },
      ],
    },
  },
  {
    // Stories live beside their component, inside src/, and the harness is the
    // whole point of them — so they are the one thing allowed up into
    // .storybook. Nothing here ships: main.ts globs stories into Storybook's
    // own build, and the app never imports a *.stories.tsx.
    files: ["**/*.stories.tsx"],
    rules: { "import/no-restricted-paths": "off" },
  },
  {
    // database.types.ts is generated by `supabase gen types` — not ours to
    // lint; scripts/ is node-run asset tooling outside the app's TS project
    ignores: [
      "eslint.config.js",
      ".prettierrc",
      "src/lib/database.types.ts",
      "scripts/**",
      "storybook-static/**",
    ],
  },
]
